Description: Creates the EonData.net website
Resources:
    # TODO: migrate eondata.net domain to Route53 to improve deployment of root domain resources. especially ACM certs like the two below.
    # NOTE: for now when first deploying this template it will not complete until the CNAME validation is completed manually in google domains.
    EonDataWebAppCert:
        Type: AWS::CertificateManager::Certificate
        Properties:
            DomainName: eondata.net
            SubjectAlternativeNames:
                - www.eondata.net
            ValidationMethod: DNS
            DomainValidationOptions:
                - DomainName: eondata.net
                  ValidationDomain: eondata.net
                - DomainName: www.eondata.net
                  ValidationDomain: eondata.net
    EonDataWebApiCert:
        Type: AWS::CertificateManager::Certificate
        Properties:
            DomainName: api.eondata.net
            ValidationMethod: DNS
            DomainValidationOptions:
                - DomainName: api.eondata.net
                  ValidationDomain: eondata.net